fix: fix workflow

diff --git a/.github/workflows/rjip_test.yml b/.github/workflows/rjip_test.yml
--- a/.github/workflows/rjip_test.yml
+++ b/.github/workflows/rjip_test.yml
@@ -20,32 +20,17 @@ jobs:
               run: |
                   curl -o data.json https://raw.githubusercontent.com/lucianoayres/brazil-stocks-tickers-json/main/b3_stocks_tickers.json
 
-            - name: Clone rjip repository
-              run: |
-                  if [ ! -d "rjip" ]; then
-                    echo "Cloning rjip repository..."
-                    git clone https://github.com/lucianoayres/rjip.git
-                  else
-                    echo "rjip directory already exists, skipping clone."
-                  fi
-
             - name: Run rjip command and handle output
               id: run_rjip
               run: |
                   #!/bin/bash
-                  set -x  # Print commands and their arguments as they are executed
+                  set -e  # Exit on error
 
                   run_rjip_command() {
                     echo "Running rjip command..."
                     cd rjip/dist
-                    if [ -f "./rjip" ]; then
-                      command_output=$(./rjip ../../data.json ticker ../../last_picks.json)
-                      echo "Command output: $command_output"
-                      cd ../..
-                    else
-                      echo "rjip binary not found!"
-                      exit 1
-                    fi
+                    command_output=$(./rjip ../../data.json ticker ../../last_picks.json || true)
+                    cd ../..
 
                     echo "$command_output" > command_output.json
                     status=$(echo "$command_output" | jq -r '.status')
@@ -78,18 +63,12 @@ jobs:
                             ;;
                         "all_items_picked")
                             echo "Error: All items have been picked and no new items are available. Message: $error_message"
-                            # Ensure correct path to last_picks.json
-                            if [ -f "last_picks.json" ]; then
-                                rm last_picks.json
-                                run_rjip_command
-                                if [ "$status" == "success" ]; then
-                                    handle_success
-                                else
-                                    echo "Retry failed with status: $status"
-                                fi
+                            rm -f ../../last_picks.json
+                            run_rjip_command
+                            if [ "$status" == "success" ]; then
+                                handle_success
                             else
-                                echo "last_picks.json not found in the root directory!"
-                                exit 1
+                                echo "Retry failed with status: $status"
                             fi
                             ;;
                         "generic_error")
